# yaml-language-server: $schema=https://spec.openapis.org/oas/3.0/schema/2021-09-28
openapi: "3.0.3"
info:
  title: make-star API
  version: 1.0.0

paths:
  /auth/signup:
    post:
      summary: ユーザー登録
      operationId: Signup
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - firstName
                - lastName
                - email
                - idToken
              properties:
                firstName:
                  type: string
                  minLength: 1
                lastName:
                  type: string
                  minLength: 1
                email:
                  type: string
                  format: email
                idToken:
                  type: string
                  minLength: 1
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SignupResponse"
        "400":
          description: Bad Request
        "409":
          description: Conflict
        "500":
          description: Internal Server Error

components:
  schemas:
    SignupResponse:
      required:
        - accessToken
        - refreshToken
      properties:
        accessToken:
          type: string
        refreshToken:
          type: string
